### ISSUE TITLE
Syntax error in utils.py

### ISSUE THREAD

**Issue by ivan-mai** [dfirsec/check_rep#6]
**Describe the bug**
Syntax error in utils.py

**Screenshots**
PS D:\Github\check_rep> python .\check_rep.py -q x.x.x.x
Traceback (most recent call last):
  File ".\check_rep.py", line 12, in <module>
    from core.geomap import map_free_geo, multi_map
  File "D:\Github\check_rep\core\geomap.py", line 10, in <module>
    from core.utils import DOMAIN, IP, Helpers, Workers, logger
  File "D:\Github\check_rep\core\utils.py", line 192
    if match := re.findall(self.query, req.text):
              ^
SyntaxError: invalid syntax

**Desktop (please complete the following information):**
OS: Windows

**Comment by dfirsec** [comment]
What version of Python are you using?  Thanks!

**Comment by AkhilNagaaroor** [comment]
I came across the same issue on Centos 7 with Python3 :-

`Traceback (most recent call last):
  File "check_rep.py", line 12, in <module>
    from core.geomap import map_free_geo, multi_map
  File "/root/check_rep/core/geomap.py", line 11, in <module>
    from core.utils import DOMAIN, IP, Helpers, Workers, logger
  File "/root/check_rep/core/utils.py", line 191
    if match := re.findall(self.query, req.text):
              ^
SyntaxError: invalid  #syntax`

**Comment by dfirsec** [comment]
I've corrected the code and replaced the named expression (Python 3.8 feature.)

**Comment by AkhilNagaaroor** [comment]
Thanks. That error was fixed but I'm getting another error :-

`Traceback (most recent call last):
  File "check_rep.py", line 14, in <module>
    from core.vt_check import VirusTotalChk
  File "/root/check_rep/core/vt_check.py", line 48
    if json_resp := json.loads(data):
                  ^
SyntaxError: invalid syntax
`

**Comment by dfirsec** [comment]
Issue resolved.
